### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by dmiric** [mrsimonemms/devpod-provider-hetzner#17]
## Is your feature request related to a problem? Please describe
Would it be possible to add snapshots. I'm not 100% sure how it could work. When you don't use machine for X days we create a snapshot and then once you want to use it again we spin a new server from that snapshot. Hetzner charges for machines by the hour even if they are not active I think spinning a machine from snapshot would be faster than provisioning a new one.

If you find this option interesting I can help you figure out the workflow.

**Comment by mrsimonemms** [comment]
It's possible, but Hetzner is _REALLY_ slow to start snapshots. It's a good idea, but I think this probably falls down in practice

**Comment by dmiric** [comment]
You are right I tested it all later and it turns out spinning up a new
machine takes almost the same time.

Sorry to bother you with this before I tested it, it simply didn't occur to
me that could be the case.

**Comment by mrsimonemms** [comment]
No problems, been there myself.
