### ISSUE TITLE
Use ssh keys to connect to machine

### ISSUE THREAD

**Issue by shyim** [mrsimonemms/devpod-provider-hetzner#3]
## Is your feature request related to a problem? Please describe
Every hetzner server created produces a email with the root password. It would be nice if ssh keys would be used for that

## Describe the behaviour you'd like
Generate short time ssh keys to not annoy my admins

**Comment by mrsimonemms** [comment]
Yeah, I like that idea.

**Comment by shyim** [comment]
I see no problem to use the same ssh key for the devpod user :)

**Comment by mrsimonemms** [comment]
Thanks.

Always one of those things that I like to get opinions on.

**Comment by shyim** [comment]
Would you mind tag a release 💙

**Comment by mrsimonemms** [comment]
Sure. I'd originally planned to do after #5 merged but can do now if needed to do that
