### ISSUE TITLE
Use Hetzner Docker Image

### ISSUE THREAD

**Issue by shyim** [mrsimonemms/devpod-provider-hetzner#5]
## Is your feature request related to a problem? Please describe
Use docker image to speed up instance creation

## Describe the behaviour you'd like
I think we can use Docker-CE image and get rid of `get.docker.com` and so on to have an general faster setup

**Comment by mrsimonemms** [comment]
There's nothing stopping you from specifying the Docker image in your settings. I guess the `runcmd` then could be to only run the `get.docker.com` command if there's no `docker` binary.

Do you know the image ID?

**Comment by shyim** [comment]
The name is `docker-ce` and the ID can be changed when they change the image docker-ce

**Comment by shyim** [comment]
I would submit a PR to change:
- default image to `docker-ce`
- when image is `docker-ce` remove docker install, curl, package upgrades

**Comment by mrsimonemms** [comment]
Yeah, I'd love to get a PR from you merged in.

The only suggestion is to not couple the installation of Docker to the `docker-ce` image, but to check if there's a docker command. I think it'll be something like...

```yaml
runcmd:
 - if docker ; then echo "Docker already installed"; else curl -fsSL https://get.docker.com | sh; fi
```

**Comment by shyim** [comment]
Ahh yes. What about removing package upgrades so the startup is faster? :) https://github.com/mrsimonemms/devpod-provider-hetzner/blob/main/pkg/hetzner/cloud-config.yaml#L15

**Comment by mrsimonemms** [comment]
Yeah, it's probably fairly unnecessary in retrospect - that's one of those things I've historically put in, but it's probably not required for a disposable workspace.

Stick that in the same PR as well if you fancy.
